# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantiers', '0003_auto_20171003_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='marche',
            name='docuemnt',
            field=models.FileField(default=1, upload_to='doc'),
            preserve_default=False,
        ),
    ]
