# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantiers', '0004_marche_docuemnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marche',
            name='docuemnt',
        ),
        migrations.AddField(
            model_name='marche',
            name='devis_doc',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marche',
            name='marche_doc',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
