# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantiers', '0005_auto_20171014_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantier',
            name='appel_1_doc',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chantier',
            name='ccmi_doc',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chantier',
            name='reception_doc',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
