# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
        ('chantiers', '0006_auto_20171015_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantier',
            name='profil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profil.Profil'),
            preserve_default=False,
        ),
    ]
