# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chantiers', '0008_chantier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chantier',
            name='profil',
        ),
    ]
