# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantiers', '0009_remove_chantier_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantier',
            name='appel_2_doc',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chantier',
            name='appel_3_doc',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chantier',
            name='appel_4_doc',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chantier',
            name='appel_5_doc',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chantier',
            name='plans_os_doc',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
