# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 06:14
from __future__ import unicode_literals

import chantiers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantiers', '0010_auto_20171016_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculeMaison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longueur_ext', models.FloatField()),
                ('largueur_ext', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='chantier',
            name='appel_1_doc',
            field=models.FileField(upload_to=chantiers.models.renommage),
        ),
        migrations.AlterField(
            model_name='chantier',
            name='appel_2_doc',
            field=models.FileField(upload_to=chantiers.models.renommage),
        ),
        migrations.AlterField(
            model_name='chantier',
            name='appel_3_doc',
            field=models.FileField(upload_to=chantiers.models.renommage),
        ),
        migrations.AlterField(
            model_name='chantier',
            name='appel_4_doc',
            field=models.FileField(upload_to=chantiers.models.renommage),
        ),
        migrations.AlterField(
            model_name='chantier',
            name='appel_5_doc',
            field=models.FileField(upload_to=chantiers.models.renommage),
        ),
        migrations.AlterField(
            model_name='chantier',
            name='ccmi_doc',
            field=models.FileField(upload_to=chantiers.models.renommage, verbose_name='CCMI'),
        ),
        migrations.AlterField(
            model_name='chantier',
            name='plans_os_doc',
            field=models.FileField(upload_to=chantiers.models.renommage),
        ),
        migrations.AlterField(
            model_name='chantier',
            name='reception_doc',
            field=models.FileField(upload_to=chantiers.models.renommage),
        ),
    ]
