# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 16:57
from __future__ import unicode_literals

import chantiers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantiers', '0012_auto_20171106_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantier',
            name='appel_6_doc',
            field=models.FileField(blank=True, upload_to=chantiers.models.renommage),
        ),
    ]
