# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantiers', '0013_chantier_appel_6_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chantier',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
