# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chantiers', '0014_auto_20171106_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Message')),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chantiers.Chantier')),
            ],
        ),
    ]
