# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chantiers', '0018_auto_20171106_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chantier',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='chantier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chantiers.Chantier'),
            preserve_default=False,
        ),
    ]
