# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 12:01
from __future__ import unicode_literals

import chantiers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chantiers', '0019_auto_20171106_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fichier', models.FileField(blank=True, upload_to=chantiers.models.renommage)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chantiers.Chantier')),
            ],
        ),
    ]
