# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 12:41
from __future__ import unicode_literals

import chantiers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantiers', '0021_auto_20171107_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chantier',
            name='appel_1_doc',
        ),
        migrations.RemoveField(
            model_name='chantier',
            name='appel_2_doc',
        ),
        migrations.RemoveField(
            model_name='chantier',
            name='appel_3_doc',
        ),
        migrations.RemoveField(
            model_name='chantier',
            name='appel_4_doc',
        ),
        migrations.RemoveField(
            model_name='chantier',
            name='appel_5_doc',
        ),
        migrations.RemoveField(
            model_name='chantier',
            name='appel_6_doc',
        ),
        migrations.RemoveField(
            model_name='chantier',
            name='ccmi_doc',
        ),
        migrations.RemoveField(
            model_name='chantier',
            name='plans_os_doc',
        ),
        migrations.RemoveField(
            model_name='chantier',
            name='reception_doc',
        ),
        migrations.AlterField(
            model_name='fichier',
            name='fichier_path',
            field=models.FileField(upload_to=chantiers.models.renommage),
        ),
    ]
