# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chantiers', '0025_delete_calculemaison'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategorieFichier',
        ),
        migrations.RemoveField(
            model_name='marche',
            name='category',
        ),
        migrations.RemoveField(
            model_name='marche',
            name='chantier',
        ),
        migrations.RemoveField(
            model_name='fichier',
            name='name',
        ),
        migrations.AddField(
            model_name='fichier',
            name='name_categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chantiers.CategorieFichier'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Marche',
        ),
    ]
