# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_ht', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PriceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ht', models.FloatField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.House')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Option')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='members',
            field=models.ManyToManyField(through='catalogue.PriceOption', to='catalogue.House'),
        ),
    ]
