# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20171109_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HouseVariante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ht', models.FloatField()),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Groupe')),
            ],
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='housevariante',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.House'),
        ),
        migrations.AddField(
            model_name='housevariante',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Variante'),
        ),
        migrations.AddField(
            model_name='house',
            name='groupes',
            field=models.ManyToManyField(through='catalogue.HouseVariante', to='catalogue.Groupe'),
        ),
    ]
