# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20171112_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseVariantePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ht', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='housevariante',
            name='variante',
        ),
        migrations.AddField(
            model_name='housevarianteprice',
            name='house_variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.HouseVariante'),
        ),
        migrations.AddField(
            model_name='housevarianteprice',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Variante'),
        ),
        migrations.AddField(
            model_name='housevariante',
            name='variantes',
            field=models.ManyToManyField(through='catalogue.HouseVariantePrice', to='catalogue.Variante'),
        ),
    ]
