# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20171112_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housevariante',
            name='variantes',
        ),
        migrations.AddField(
            model_name='housevariante',
            name='variantes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Variante'),
            preserve_default=False,
        ),
    ]
