# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20171112_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housevariante',
            name='price_ht',
        ),
        migrations.RemoveField(
            model_name='housevariante',
            name='variantes',
        ),
        migrations.AddField(
            model_name='housevariante',
            name='variantes',
            field=models.ManyToManyField(through='catalogue.HouseVariantePrice', to='catalogue.Variante'),
        ),
    ]
