# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20171113_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housevarianteprice',
            name='house_variante',
        ),
        migrations.RemoveField(
            model_name='housevarianteprice',
            name='variante',
        ),
        migrations.RemoveField(
            model_name='option',
            name='category',
        ),
        migrations.RemoveField(
            model_name='option',
            name='members',
        ),
        migrations.RemoveField(
            model_name='priceoption',
            name='house',
        ),
        migrations.RemoveField(
            model_name='priceoption',
            name='option',
        ),
        migrations.RemoveField(
            model_name='house',
            name='groupes',
        ),
        migrations.RemoveField(
            model_name='housevariante',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='housevariante',
            name='variantes',
        ),
        migrations.AddField(
            model_name='house',
            name='variantes',
            field=models.ManyToManyField(through='catalogue.HouseVariante', to='catalogue.Variante'),
        ),
        migrations.AddField(
            model_name='housevariante',
            name='price_ht',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housevariante',
            name='variante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Variante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variante',
            name='groupe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Groupe'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CategoryOption',
        ),
        migrations.DeleteModel(
            name='HouseVariantePrice',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='PriceOption',
        ),
    ]
