# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20171113_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='housevariante',
            name='groupe',
            field=models.ManyToManyField(to='catalogue.Groupe'),
        ),
    ]
