# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20171113_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declinaison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='catalogue.Groupe')),
            ],
        ),
        migrations.CreateModel(
            name='DeclinaisonPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ht', models.FloatField()),
                ('declinaison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declinaisons', to='catalogue.Declinaison')),
            ],
        ),
        migrations.AlterField(
            model_name='house',
            name='groupes',
            field=models.ManyToManyField(through='catalogue.Declinaison', to='catalogue.Groupe'),
        ),
        migrations.AlterField(
            model_name='variante',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogue.Groupe'),
        ),
        migrations.AddField(
            model_name='declinaisonprice',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogue.Variante'),
        ),
        migrations.AddField(
            model_name='declinaison',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='catalogue.House'),
        ),
        migrations.AddField(
            model_name='declinaison',
            name='variantes',
            field=models.ManyToManyField(through='catalogue.DeclinaisonPrice', to='catalogue.Variante'),
        ),
    ]
