# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0013_auto_20171113_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declinaison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DeclinaisonPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ht', models.FloatField()),
                ('declinaison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declinaisons', to='catalogue.Declinaison')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_ht', models.FloatField()),
                ('code', models.CharField(blank=True, max_length=100)),
                ('groupes', models.ManyToManyField(to='catalogue.Groupe')),
            ],
        ),
        migrations.CreateModel(
            name='HouseVariante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ht', models.FloatField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.House')),
            ],
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='housevariante',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Variante'),
        ),
        migrations.AddField(
            model_name='declinaisonprice',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogue.Variante'),
        ),
        migrations.AddField(
            model_name='declinaison',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='catalogue.Groupe'),
        ),
        migrations.AddField(
            model_name='declinaison',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='catalogue.House'),
        ),
        migrations.AddField(
            model_name='declinaison',
            name='variantes',
            field=models.ManyToManyField(through='catalogue.DeclinaisonPrice', to='catalogue.Variante'),
        ),
    ]
