# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20171113_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='groupes',
            field=models.ManyToManyField(through='catalogue.Declinaison', to='catalogue.Groupe'),
        ),
    ]
