# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20171113_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declinaison',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='declinaison',
            name='house',
        ),
        migrations.RemoveField(
            model_name='declinaison',
            name='variantes',
        ),
        migrations.RemoveField(
            model_name='declinaisonprice',
            name='declinaison',
        ),
        migrations.RemoveField(
            model_name='declinaisonprice',
            name='variante',
        ),
        migrations.RemoveField(
            model_name='housevariante',
            name='house',
        ),
        migrations.RemoveField(
            model_name='housevariante',
            name='variante',
        ),
        migrations.DeleteModel(
            name='Declinaison',
        ),
        migrations.DeleteModel(
            name='DeclinaisonPrice',
        ),
        migrations.DeleteModel(
            name='Groupe',
        ),
        migrations.DeleteModel(
            name='HouseVariante',
        ),
        migrations.DeleteModel(
            name='Variante',
        ),
    ]
